# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- dev/*

pr:
  branches:
    include:
      - master
      - dev/*

pool:
  vmImage: 'windows-latest'

variables:
  projects: '**/*.csproj'
  buildConfiguration: 'Release'
  publishDirectory: '$(System.DefaultWorkingDirectory)/publish'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '$(projects)'
      feedsToUse: 'select'
      vstsFeed: '51fdd28c-c4da-456a-8855-685a5e5021ea'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: '$(projects)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '$(projects)'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '$(projects)'
      arguments: '--configuration $(buildConfiguration) --output $(publishDirectory)'
      zipAfterPublish: false

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(publishDirectory)'
      includeRootFolder: false
      archiveFile: '$(publishDirectory)/build$(Build.BuildId).zip'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(publishDirectory)/build$(Build.BuildId).zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'